import Head from "next/head";
import styles from "../styles/Home.module.css";
import { AudioPlayer } from "../components/AudioPlayer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dribbling Mac</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg'  width='32' height='32' viewport='0 0 100 100' style='fill:black;font-size:24px;'><text y='80%'>👾</text></svg>"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Graduate&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <main className={styles.main}>
        <AudioPlayer />
      </main>
    </div>
  );
}
