import Head from "next/head";
import styles from "../styles/Home.module.css";
import { AudioPlayer } from "../components/AudioPlayer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dribbling Mac</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Graduate&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <main className={styles.main}>
        <AudioPlayer />
      </main>
    </div>
  );
}
